// Array de objetos para el E-commerce

const productos = [
    {
        id: 1,
        nombreProducto: "Naranja",
        precio: 500,
        presentacion: "docena",
        detalle: "Naranja tipo tangelo para jugo",
        categoria: "Frutas",
        oferta: true,
    },
    {
        id: 2,
        nombreProducto: "Mandarina",
        precio: 500,
        presentacion: "media docena",
        detalle: "Mandarina dulce para jugo",
        categoria: "Frutas",
        oferta: true,
    },
    {
        id: 3,
        nombreProducto: "Limon",
        precio: 600,
        presentacion: "media docena",
        detalle: "Limón para preparaciones y bebidas",
        categoria: "Frutas",
        oferta: true,
    },
    {
        id: 4,
        nombreProducto: "Uva",
        precio: 700,
        presentacion: "paquete",
        detalle: "Uva tipo isabelina",
        categoria: "Frutas",
        oferta: false,
    },
    {
        id: 5,
        nombreProducto: "Papaya",
        precio: 800,
        presentacion: "unidad",
        detalle: "Papaya madura",
        categoria: "Frutas",
        oferta: false,
    },
    {
        id: 6,
        nombreProducto: "Cebolla",
        precio: 600,
        presentacion: "media docena",
        detalle: "Cebolla tipo cabezona para preparaciones",
        categoria: "Verduras",
        oferta: true,
    },
    {
        id: 7,
        nombreProducto: "Tomate",
        precio: 600,
        presentacion: "media docena",
        detalle: "Tomate verde para ensaladas",
        categoria: "Verduras",
        oferta: false,
    },
    {
        id: 8,
        nombreProducto: "Apio",
        precio: 700,
        presentacion: "racimo",
        detalle: "Apio verde para preparaciones",
        categoria: "Verduras",
        oferta: false,
    },
    {
        id: 9,
        nombreProducto: "Lechuga",
        precio: 500,
        presentacion: "unidad",
        detalle: "Lechuga crespa para preparaciones",
        categoria: "Verduras",
        oferta: true,
    },
    {
        id: 10,
        nombreProducto: "Brocoli",
        precio: 800,
        presentacion: "unidad",
        detalle: "Racimo de brocoli para preparar",
        categoria: "Verduras",
        oferta: false,
    },
    {
        id: 11,
        nombreProducto: "Res",
        precio: 400,
        presentacion: "libra",
        detalle: "libra de carne de res",
        categoria: "Carnicos",
        oferta: true,
    },
    {
        id: 12,
        nombreProducto: "Pollo",
        precio: 800,
        presentacion: "unidad",
        detalle: "prechuga de pollo criollo",
        categoria: "Carnicos",
        oferta: true,
    },

    {
        id: 13,
        nombreProducto: "Pescado",
        precio: 900,
        presentacion: "unidad",
        detalle: "filete de pescado",
        categoria: "Carnicos",
        oferta: false,
    },
    {
        id: 14,
        nombreProducto: "Cerdo",
        precio: 500,
        presentacion: "libra",
        detalle: "libra de carne de cerdo",
        categoria: "Carnicos",
        oferta: true,
    },
    {
        id: 15,
        nombreProducto: "Gallina",
        precio: 500,
        presentacion: "unidad",
        detalle: "pechuga de gallina criolla",
        categoria: "Carnicos",
        oferta: false,
    } 
]